spring.datasource.url=jdbc:postgresql://localhost:5432/infSystem
spring.datasource.username=postgres
spring.datasource.password=1424

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
