spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/infSystem
    username: postgres
    password: 1424
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  security:
    user:
      name: user
      password: 0000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

